backend:
  name: github
  repo: ishaq74/wafflecoffee #replace with your github repo
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://wafflecoffeeannecy.netlify.app/" # your site name

collections:
  - name: post
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    preview_path: post/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: date }
      - {label: "Publish", name: "isPublish", widget: "boolean", default: true}
      - {label: "Draft", name: "isDraft", widget: "boolean", default: false}
      - { name: body, label: Body, widget: markdown }
  
  - name: big-bubble
    label: "Big Bubble"
    folder: src/content/big-bubble
    create: true
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: price, label: Price, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: image, label: Image, widget: image }
      - { name: image_alt, label: "Image Alt Text", widget: string }

  - name: pancakes
    label: Pancakes
    folder: src/content/pancakes
    create: true
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: price, label: Price, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: image, label: Image, widget: image }
      - { name: image_alt, label: "Image Alt Text", widget: string }

  - name: crepes-sucrees
    label: "Crêpes Sucrées"
    folder: src/content/crepes-sucrees
    create: true
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: price, label: Price, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: image, label: Image, widget: image }
      - { name: image_alt, label: "Image Alt Text", widget: string }

  - name: yaourts-glaces
    label: "Yaourts Glacés"
    folder: src/content/yaourts-glaces
    create: true
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: price, label: Price, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: image, label: Image, widget: image }
      - { name: image_alt, label: "Image Alt Text", widget: string }

  - name: cafes
    label: Cafés
    folder: src/content/cafes
    create: true
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: price, label: Price, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: image, label: Image, widget: image }
      - { name: image_alt, label: "Image Alt Text", widget: string }

  - name: thes
    label: Thés
    folder: src/content/thes
    create: true
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: price, label: Price, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: image, label: Image, widget: image }
      - { name: image_alt, label: "Image Alt Text", widget: string }

  - name: boissons
    label: Boissons
    folder: src/content/boissons
    create: true
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: price, label: Price, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: image, label: Image, widget: image }
      - { name: image_alt, label: "Image Alt Text", widget: string }

  - name: smoothies
    label: Smoothies
    folder: src/content/smoothies
    create: true
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: price, label: Price, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: image, label: Image, widget: image }
      - { name: image_alt, label: "Image Alt Text", widget: string }

  - name: milkshakes
    label: Milkshakes
    folder: src/content/milkshakes
    create: true
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: price, label: Price, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: image, label: Image, widget: image }
      - { name: image_alt, label: "Image Alt Text", widget: string }
